---
- name: Install system compile packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ kickstart_iso_compile_packages }}"

- name: Compile xorriso
  become: true
  shell: |
    mkdir -p /tmp/xorriso
    cd /tmp/xorriso
    wget https://ftp.gnu.org/gnu/xorriso/xorriso-1.5.2.tar.gz
    tar xzf xorriso-1.5.2.tar.gz
    cd xorriso-1.5.2
    ./configure --prefix=/usr
    make
    ./xorriso/xorriso
    make buildstamped
    strip ./xorriso/xorriso
    make install
    rm -rf /tmp/xorriso
  args:
    warn: no

- name: Verify xorriso
  command: xorriso -version
  register: kickstart_iso_xorriso_check
