---
- name: Prepare
  hosts: all
  gather_facts: no
  become: yes

  tasks:
  - include_role:
      name: rembik.bootstrap

  - name: Ensure images cache exits
    stat:
      path: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/.images"
    register: molecule_image_cache

  - name: Copy images cache
    copy:
      src: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/.images"
      dest: ".images"
      mode: 0755
      decrypt: no
    when:
      - molecule_image_cache.stat.exists
      - molecule_image_cache.stat.isdir
