---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  # https://app.vagrantup.com/boxes/search
  - name: "${TEST_INSTANCE_PREFIX:-instance}_${TEST_DISTRO:-centos_latest}_vagrant"
    image: ${TEST_VBOX:-centos/8}
    groups:
      - ${TEST_DISTRO:-centos_latest}_vagrant
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_plugins: /usr/lib/python${TEST_PYTHON_VERSION:-3.9}/site-packages/ara/plugins/callbacks
  playbooks:
    converge: ${TEST_CONVERGE:-../resources/converge.yml}
    verify: ${TEST_VERIFY:-../resources/verify.yml}
scenario:
  name: vagrant
verifier:
  name: ansible
