---
dependency:
  name: galaxy
  options:
    role-file: molecule/resources/requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  # https://hub.docker.com/search/?type=image
  - name: instance_alpine_latest_docker
    image: alpine:latest
    pre_build_image: yes
    command: "sh -c 'sleep infinity & wait'"
    groups:
      - alpine_latest_docker
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/.images/base:/tmp/images/base:ro
  - name: instance_centos_latest_docker
    image: centos:latest
    pre_build_image: yes
    groups:
      - centos_latest_docker
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/.images/base:/tmp/images/base:ro
  - name: instance_debian_latest_docker
    image: debian:latest
    pre_build_image: yes
    groups:
      - debian_latest_docker
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/.images/base:/tmp/images/base:ro
  - name: instance_fedora_latest_docker
    image: fedora:latest
    pre_build_image: yes
    groups:
      - fedora_latest_docker
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/.images/base:/tmp/images/base:ro
  - name: instance_opensuse_leap_docker
    image: opensuse/leap:latest
    pre_build_image: yes
    groups:
      - opensuse_leap_docker
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/.images/base:/tmp/images/base:ro
  - name: instance_opensuse_tumbleweed_docker
    image: opensuse/tumbleweed:latest
    pre_build_image: yes
    groups:
      - opensuse_tumbleweed_docker
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/.images/base:/tmp/images/base:ro
  - name: instance_redhat_latest_docker
    image: registry.access.redhat.com/ubi8/ubi:latest
    pre_build_image: yes
    groups:
      - redhat_latest_docker
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/.images/base:/tmp/images/base:ro
  - name: instance_ubuntu_latest_docker
    image: ubuntu:latest
    pre_build_image: yes
    groups:
      - ubuntu_latest_docker
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/.images/base:/tmp/images/base:ro
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callbacks_enabled: ansible.posix.profile_tasks, ansible.posix.timer, community.general.yaml
      stdout_callback: community.general.yaml
  playbooks:
    docker:
      prepare: ${TEST_PREPARE:-../resources/docker/prepare.yml}
    prepare: ${TEST_PREPARE:-../resources/prepare.yml}
    converge: ${TEST_CONVERGE:-../resources/converge.yml}
    verify: ${TEST_VERIFY:-../resources/verify.yml}
scenario:
  name: docker-all-latest
verifier:
  name: ansible
