---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  # https://hub.docker.com/search/?type=image
  - name: "${TEST_INSTANCE_PREFIX:-instance}_${TEST_DISTRO:-centos_latest}_${TOX_ENVNAME:-docker}"
    image: ${TEST_DOCKER_IMAGE:-centos:latest}
    pre_build_image: yes
    command: ${TEST_DOCKER_COMMAND:-"bash -c 'sleep infinity & wait'"}
    groups:
      - ${TEST_DISTRO:-centos_latest}_docker
provisioner:
  name: ansible
  ansible_args:
    - -vvvv
  config_options:
    defaults:
      stdout_callback: yaml
      callback_plugins: /usr/lib/python${TEST_PYTHON_VERSION:-3.9}/site-packages/ara/plugins/callbacks
  playbooks:
    converge: ${TEST_CONVERGE:-../resources/converge.yml}
    verify: ${TEST_VERIFY:-../resources/verify.yml}
scenario:
  name: default
verifier:
  name: ansible
