---
dependency:
  name: galaxy
  options:
    role-file: molecule/resources/requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  # https://hub.docker.com/search/?type=image
  - name: "${TEST_INSTANCE_PREFIX:-instance}_${TEST_DISTRO:-centos_latest}_${TOX_ENVNAME:-docker}"
    image: ${TEST_DOCKER_IMAGE:-centos:latest}
    pre_build_image: yes
    command: ${TEST_DOCKER_COMMAND:-"bash -c 'sleep infinity & wait'"}
    groups:
      - ${TEST_DISTRO:-centos_latest}_docker
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/.images/base:/tmp/images/base:ro
provisioner:
  name: ansible
  # ansible_args:
  #  - -vvvv
  config_options:
    defaults:
      interpreter_python: auto_silent
      callbacks_enabled: ansible.posix.profile_tasks, ansible.posix.timer, community.general.yaml
      stdout_callback: community.general.yaml
  playbooks:
    docker:
      prepare: ${TEST_PREPARE:-../resources/docker/prepare.yml}
    prepare: ${TEST_PREPARE:-../resources/prepare.yml}
    converge: ${TEST_CONVERGE:-../resources/converge.yml}
    verify: ${TEST_VERIFY:-../resources/verify.yml}
scenario:
  name: default
verifier:
  name: ansible
