---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  # https://hub.docker.com/search/?type=image
  - name: "${TEST_INSTANCE_PREFIX:-instance}_${TEST_DISTRO:-centos_latest}_${TOX_ENVNAME:-docker}"
    image: ${TEST_DOCKER_IMAGE:-centos:latest}
    pre_build_image: yes
    command: ${TEST_DOCKER_COMMAND:-""}
    groups:
      - ${TEST_DISTRO:-centos_latest}_docker
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_plugins: /usr/lib/python${GITHUB_PYTHON_VERSION:-3.8}/site-packages/ara/plugins/callbacks
  playbooks:
    converge: ${TEST_PLAYBOOK:-../converge.yml}
scenario:
  name: default
verifier:
  name: ansible
