---
name: CI
on:
  schedule:
    - cron: '0 22 15 * *'  # every 15th day of month at 22:00
  push:
    branches:
      - 'master'
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+*'
  pull_request:

jobs:

  test:
    name: Molecule
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        distro:
          - alpine-latest
          - amazonlinux-latest
          - centos-latest
          - debian-latest
          - fedora-latest
          - opensuse-leap
          - opensuse-tumbleweed
          - redhat-latest
          - ubuntu-latest
        ansible: [stable]
        python-version: [3.9]
        experimental: [false]
        include:
          - {distro: alpine-latest, ansible: devel, python-version: 3.9, experimental: true}
          - {distro: amazonlinux-latest, ansible: devel, python-version: 3.9, experimental: true}
          - {distro: debian-latest, ansible: devel, python-version: 3.9, experimental: true}
          - {distro: fedora-latest, ansible: devel, python-version: 3.9, experimental: true}
          - {distro: opensuse-leap, ansible: devel, python-version: 3.9, experimental: true}
          - {distro: opensuse-tumbleweed, ansible: devel, python-version: 3.9, experimental: true}
          - {distro: redhat-latest, ansible: devel, python-version: 3.9, experimental: true}
          - {distro: ubuntu-latest, ansible: devel, python-version: 3.9, experimental: true}
          - {distro: alpine-edge, ansible: all, python-version: 3.9, experimental: true}
          - {distro: debian-unstable, ansible: all, python-version: 3.9, experimental: true}
          - {distro: fedora-rawhide, ansible: all, python-version: 3.9, experimental: true}
          - {distro: ubuntu-devel, ansible: all, python-version: 3.9, experimental: true}

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set environment variables
        id: prep
        run: |
          case "${{ matrix.distro }}" in
            alpine-latest)  DOCKER_IMAGE="alpine:latest";;
            alpine-edge)  DOCKER_IMAGE="alpine:edge";;
            amazonlinux-latest)  DOCKER_IMAGE="amazonlinux:latest";;
            centos-latest)  DOCKER_IMAGE="centos:latest";;
            debian-latest)  DOCKER_IMAGE="debian:latest";;
            debian-unstable)  DOCKER_IMAGE="debian:unstable";;
            fedora-latest)  DOCKER_IMAGE="fedora:latest";;
            fedora-rawhide)  DOCKER_IMAGE="fedora:rawhide";;
            opensuse-leap)  DOCKER_IMAGE="opensuse/leap:latest";;
            opensuse-tumbleweed)  DOCKER_IMAGE="opensuse/tumbleweed:latest";;
            redhat-latest)  DOCKER_IMAGE="registry.access.redhat.com/ubi8/ubi:latest";;
            ubuntu-latest)  DOCKER_IMAGE="ubuntu:latest";;
            ubuntu-devel)  DOCKER_IMAGE="ubuntu:devel";;
          esac
          echo ::set-output name=docker-image::${DOCKER_IMAGE}
          if [[ "${{ matrix.distro }}" == alpine* ]]; then
            DOCKER_COMMAND="sh -c 'trap : TERM INT; sleep 9999999999d & wait'"
          fi
          echo ::set-output name=docker-command::${DOCKER_COMMAND:-}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions

      - name: Test with molecule
        timeout-minutes: 60
        run: |
          tox
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          ANSIBLE: ${{ matrix.ansible }}
          TEST_PYTHON_VERSION: ${{ matrix.python-version }}
          TEST_DISTRO: ${{ matrix.distro }}
          TEST_DOCKER_IMAGE: ${{ steps.prep.outputs.docker-image }}
          TEST_DOCKER_COMMAND: ${{ steps.prep.outputs.docker-command }}
